const passport = require("passport");
const GoogleStrategy = require("passport-google-oauth20").Strategy;
const mongoose = require("mongoose");
const keys = require("../config/keys");

const User = mongoose.model("users");

// take user from db and generate indetifier
// user.id = id generated by mongo
passport.serializeUser((user, done) => {
  done(null, user.id);
});

// take user.id and find then user by id
passport.deserializeUser((id, done) => {
  User.findById(id).then(user => {
    done(null, user);
  });
});

passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: "/auth/google/callback",
      proxy: true
    },
    async (accessToken, refreshToken, profile, done) => {
      const existingUser = await User.findOne({ googleID: profile.id });
      if (existingUser) {
        // if we have record of user, do not duplicate
        return done(null, existingUser);
      }
      // if no such user, create new one
      const user = await new User({ googleID: profile.id }).save();
      done(null, user);
    }
  )
);
